# ================================
# _config.yml — Shahrouz Jafarzadeh
# Fill anything marked with:  <<< EDIT ME
# ================================

# Basic Site Settings
locale      : "en-US"
site_theme  : "default"       # options: "default", "air"
title       : "Shahrouz Jafarzadeh — Quantitative Finance"
title_separator: "-"
name        : &name "Shahrouz Jafarzadeh"
description : &description "Academic portfolio — Quantitative Finance, Risk Modeling, Data Science"
url         : https://shahrouzjafarzadeh.com        # keep until you connect your custom domain
baseurl     : ""                                     # do not change
repository  : "Shahrouz-Zada/shahrouzjafarzadeh.github.io"

# Sidebar / Author block
author:
  avatar     : "profile.png"   # put your headshot at /images/profile.png
  name       : "Shahrouz Jafarzadeh"
  pronouns   :                 # optional (e.g., "he/him")
  bio        : "Doctorate in Quantitative Finance. Teaches Financial Modeling, Python for Finance, Data Analysis, and ML/AI for Finance and Marketing. Industry: Natixis & Nexus Horizon."  # keep concise
  location   : "France"        # <<< EDIT ME if you'd like city: "Paris, France"
  employer   : "Nexus Horizon" # <<< EDIT ME if needed
  uri        :
  email      : "contact@YOUR-DOMAIN.com"  # <<< EDIT ME

  # Academic profiles (add only what you have)
  academia      :
  arxiv         :
  googlescholar :   # <<< EDIT ME (replace YOUR_ID)
  impactstory   :
  orcid         :     # <<< EDIT ME or remove
  semantic      :
  pubmed        :
  researchgate  :   # <<< EDIT ME or remove
  scopus        :

  # Dev / repos
  github        : "Shahrouz-Zada"
  kaggle        :
  stackoverflow :

  # Social (add only what you use)
  bluesky       :             
  linkedin      : "your-linkedin-handle"   # <<< EDIT ME (just handle or full URL)
  mastodon      :
  medium        :
  twitter       :               # X/Twitter handle (no @)
  youtube       :

# Publication Categories (labels on your publications page)
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# Site Settings
teaser          :
breadcrumbs     : false
words_per_minute: 160
future          : true
read_more       : "disabled"
talkmap_link    : false

comments:
  provider      :               # keep blank unless you set up Disqus/etc.

staticman:
  allowedFields : ['name','email','url','message']
  branch        : "gh-pages"
  commitMessage : "New comment."
  filename      : "comment-{@timestamp}"
  format        : "yml"
  moderation    : true
  path          : "_data/comments/{options.slug}"
  requiredFields: ['name','email','message']
  transforms:
    email       : "md5"
  generatedFields:
    date:
      type      : "date"
      options:
        format  : "iso8601"

atom_feed:
  hide          : false
  path          :

# SEO
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing (OpenGraph defaults)
twitter:
  username      :
facebook:
  username      :
  app_id        :
  publisher     :
og_image        :  # e.g., "/images/og-card.png"
og_description  :

# Organization/Person JSON-LD
social:
  type          : "Person"
  name          : "Shahrouz Jafarzadeh"
  links:        # add full profile URLs here (optional)
    # - https://www.linkedin.com/in/your-handle
    # - https://github.com/Shahrouz-Zada

# Analytics (optional)
analytics:
  provider      : "false"       # set to "google-analytics-4" when ready
  google:
    tracking_id :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - ".sublime-project"
  - ".sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding    : "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown         : kramdown
highlighter      : rouge
lsi              : false
excerpt_separator: "\n\n"
incremental      : false

# Markdown Processing
kramdown:
  input       : GFM
  hard_wrap   : false
  auto_ids    : true
  footnote_nr : 1
  entity_output: as_char
  toc_levels  : 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections (enable built-in sections)
collections:
  teaching:
    output   : true
    permalink: /:collection/:path/
  publications:
    output   : true
    permalink: /:collection/:path/
  portfolio:
    output   : true
    permalink: /:collection/:path/
  talks:
    output   : true
    permalink: /:collection/:path/

# Defaults for pages/collections
defaults:
  - scope: { path: "", type: posts }
    values:
      layout        : single
      author_profile: true
      read_time     : true
      comments      : true
      share         : true
      related       : true

  - scope: { path: "", type: pages }
    values:
      layout        : single
      author_profile: true

  - scope: { path: "", type: teaching }
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : true

  - scope: { path: "", type: publications }
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : true

  - scope: { path: "", type: portfolio }
    values:
      layout        : single
      author_profile: true
      share         : true
      comment       : true

  - scope: { path: "", type: talks }
    values:
      layout        : talk
      author_profile: true
      share         : true

# Sass
sass:
  sass_dir: _sass
  style  : compressed

# Output
permalink: /:categories/:title/
timezone : Europe/Paris   # <<< EDIT ME if different

# Plugins (GitHub Pages-compatible)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
